using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AcharDomainCore.Entites;

namespace Achar.Infra.Db.SqLServer.EntitiesConfigration
{
    public class HomeServiceConfig : IEntityTypeConfiguration<AcharDomainCore.Entites.HomeService>
    {
        public void Configure(EntityTypeBuilder<AcharDomainCore.Entites.HomeService> builder)
        {
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Title)
                .IsRequired()
                .HasMaxLength(100);
            builder
                .Property(x => x.BasePrice)
                .IsRequired();
            builder.Property(x => x.Description)
                .HasColumnType("nvarchar(MAX)");

            builder.Property(x => x.IsDeleted)
                .HasDefaultValue(false);

            builder
                .HasOne(x => x.SubCategory)
                .WithMany(y => y.HomeServices)
                .HasForeignKey(x => x.SubCategoryId)
                .OnDelete(DeleteBehavior.NoAction);

            builder
                .HasMany(x => x.Requests)
                .WithOne(y => y.Service)
                .HasForeignKey(y => y.HomeServiceId)
                .OnDelete(DeleteBehavior.NoAction);



            builder.HasData(
                new AcharDomainCore.Entites.HomeService { Id = 1, Title = "سرویس عادی نظافت", SubCategoryId = 1, IsDeleted = false,
                    Description = "سرویس عادی نظافت شامل تمیزکاری کلی محیط، گردگیری سطوح، جارو و تی کشی است. این سرویس برای حفظ نظافت روزمره و ایجاد فضایی پاک و مرتب ارائه میشود.",
                    ImageSrc = "/assets/img/homeservice/1.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 2, Title = "سرویس وِیژه نظافت", SubCategoryId = 1, IsDeleted = false,
                    Description = "سرویس ویژه نظافت شامل تمیزکاری عمیق و تخصصی با استفاده از مواد و تجهیزات حرفه ای است. این سرویس برای پاک سازی کامل و ضدعفونی محیط های مسکونی و اداری ارائه میشود.",
                    ImageSrc = "/assets/img/homeservice/2.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 3, Title = "نظافت راه پله", SubCategoryId = 1, IsDeleted = false,
                    Description = "سرویس نظافت راه پله شامل جارو و تی کشی پله ها، پاکسازی نرده ها، دستگیره ها و ورودی ساختمان است. این سرویس به حفظ تمیزی و زیبایی مشاعات کمک می کند.",
                    ImageSrc = "/assets/img/homeservice/3.jpg", BasePrice = 500000 },
                new AcharDomainCore.Entites.HomeService { Id = 4, Title = "پذیرایی", SubCategoryId = 1, IsDeleted = false,
                    Description = "سرویس پذیرایی شامل چیدمان، سرو غذا و نوشیدنی، نظافت میزها و رسیدگی به مهمانان است این سرویس برای مراسم، مهمانی ها و جلسات ارائه میشود",
                    ImageSrc = "/assets/img/homeservice/4.jpg", BasePrice = 1500000 },
                new AcharDomainCore.Entites.HomeService { Id = 5, Title = "کارگرساده", SubCategoryId = 1, IsDeleted = false,
                    Description = "سرویس کارگر ساده شامل انجام امور عمومی مانند جابه جایی وسایل، کمک در نظافت، انبارداری و سایر کارهای دستی است. این سرویس برای مصارف خانگی و صنعتی ارائه میشود.",
                    ImageSrc = "/assets/img/homeservice/5.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 6, Title = "فینگرفود", SubCategoryId = 3, IsDeleted = false,
                    Description = "سرویس فینگرفود شامل تهیه و سرو انواع خوراکیهای لقمهای شیک و خوشمزه برای مهمانیها، مراسم و جلسات است. این سرویس تنوعی از طعمها را با دیزاینی جذاب ارائه میدهد.",
                    ImageSrc = "/assets/img/homeservice/6.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 7, Title = "فست فود", SubCategoryId = 3, IsDeleted = false,
                    Description = "سرویس فست  شامل تهیه و ارائه انواع غذاهای سریع و لذیذ مانند برگر، پیتزا، ساندویچ و سیب  سرخ  است. این سرویس برای مجالس، مهمانی  و رویدادهای مختلف ارائه میشود.", 
                    ImageSrc = "/assets/img/homeservice/7.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 8, Title = "غذای ایرانی", SubCategoryId = 3, IsDeleted = false,
                    Description = "سرویس غذای ایرانی شامل تهیه و سرو انواع غذاهای سنتی و اصیل ایرانی مانند کباب، قورمه ، قیمه و باقالی  است. این سرویس برای مهمانی ، مراسم و رویدادهای خاص ارائه میشود.",
                    ImageSrc = "/assets/img/homeservice/8.jpg", BasePrice = 250000 },
                new AcharDomainCore.Entites.HomeService { Id = 9, Title = "تعمیر و سرویس پکیج", SubCategoryId = 4, IsDeleted = false,
                    Description = "سرویس تعمیر و نگهداری پکیج شامل عیب ، رسوب ، تنظیم فشار، هواگیری و تعمیر قطعات معیوب است. این سرویس برای بهبود عملکرد و افزایش عمر مفید پکیج ارائه میشود.",
                    ImageSrc = "/assets/img/homeservice/9.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 10, Title = "تعمیر و سرویس آبگرمکن", SubCategoryId = 4, IsDeleted = false,
                    Description = "سرویس تعمیر و نگهداری آبگرمکن شامل عیب ، رسوب ، تنظیم شعله، تعویض قطعات معیوب و هواگیری است. این سرویس برای بهبود عملکرد و افزایش عمر مفید آبگرمکن ارائه میشود.", 
                    ImageSrc = "/assets/img/homeservice/10.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 11, Title = "تعمیر و سرویس فن کویل", SubCategoryId = 4, IsDeleted = false,
                    Description = "سرویس تعمیر و نگهداری فن شامل تمیز کردن فیلترها، بررسی عملکرد موتور، تنظیم دما و فشار آب، و عیب یابی سیستم برقی است. این سرویس به بهبود عملکرد فن کوئل و افزایش کارایی سیستم تهویه کمک میکند.",
                    ImageSrc = "/assets/img/homeservice/11.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 12, Title = "تعمیر کولرگازی و داکت اسپلیت", SubCategoryId = 4, IsDeleted = false,
                    Description = "سرویس تعمیر و نگهداری کولرگازی و داکت اسپلیت شامل بررسی عملکرد کمپرسور، تمیز کردن فیلترها، شارژ گاز، عیب یابی قطعات الکتریکی و مکانیکی، و تنظیم دما است. این سرویس به بهبود عملکرد و طول عمر دستگاه ها کمک میکند.",
                    ImageSrc = "/assets/img/homeservice/12.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 13, Title = "تعمیر و سرویس کولر آبی", SubCategoryId = 4, IsDeleted = false, 
                    Description = "سرویس تعمیر و نگهداری کولر آبی شامل تمیز کردن پوشال\u200cها، بررسی موتور و پمپ آب، تنظیم شیب لوله\u200cها، تعویض قطعات فرسوده و تنظیم عملکرد فن است. این سرویس به بهبود کارایی کولر و افزایش عمر مفید آن کمک می\u200cکند.",
                    ImageSrc = "/assets/img/homeservice/13.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 14, Title = "سنگ کاری", SubCategoryId = 5, IsDeleted = false, 
                    Description = "سرویس سنگ\u200cکاری شامل نصب، ترمیم و صیقل دادن انواع سنگ\u200cها در کف، دیوار و سطوح مختلف است. این سرویس برای زیبا\u200cسازی و استحکام فضاهای داخلی و خارجی مانند ساختمان\u200cها، حیاط\u200cها و محوطه\u200cهای عمومی ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/14.jpg", BasePrice = 3000000 },
                new AcharDomainCore.Entites.HomeService { Id = 15, Title = "نقاشی ساختمان", SubCategoryId = 5, IsDeleted = false,
                    Description = "سرویس نقاشی ساختمان شامل رنگ\u200cآمیزی دیوارها، سقف\u200cها، درب\u200cها و پنجره\u200cها با استفاده از رنگ\u200cهای مرغوب و تکنیک\u200cهای حرفه\u200cای است. این سرویس برای ایجاد ظاهری زیبا و تازه برای فضاهای داخلی و خارجی ساختمان ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/15.jpg", BasePrice = 3000000 },
                new AcharDomainCore.Entites.HomeService { Id = 16, Title = "نصب کاغذ دیواری", SubCategoryId = 5, IsDeleted = false,
                    Description = "سرویس نصب کاغذ دیواری شامل اندازه\u200cگیری دقیق دیوارها، انتخاب و نصب کاغذ دیواری با طراحی و رنگ دلخواه است. این سرویس برای زیباسازی فضاهای داخلی و ایجاد جلوه\u200cای خاص و شیک در خانه\u200cها و ادارات ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/16.jpg", BasePrice = 250000 },
                new AcharDomainCore.Entites.HomeService { Id = 17, Title = "دوخت و نصب پرده", SubCategoryId = 5, IsDeleted = false, 
                    Description = "سرویس دوخت و نصب پرده شامل طراحی، اندازه\u200cگیری، دوخت پرده متناسب با دکوراسیون و نصب حرفه\u200cای آن است. این سرویس برای زیباسازی و تنظیم نور فضاهای مسکونی و اداری ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/17.jpg", BasePrice = 250000 },
                new AcharDomainCore.Entites.HomeService { Id = 18, Title = "بنایی", SubCategoryId = 5, IsDeleted = false,
                    Description = "سرویس بنایی شامل ساخت، تعمیر و بازسازی بخش\u200cهای مختلف ساختمان مانند دیوارچینی، کف\u200cسازی، گچ\u200cکاری و سیمان\u200cکاری است. این سرویس برای مقا\u200cم\u200cسازی و زیباسازی فضاهای مسکونی، اداری و تجاری ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/18.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 19, Title = "کلیدسازی", SubCategoryId = 5, IsDeleted = false, 
                    Description = "سرویس کلیدسازی شامل ساخت انواع کلید، باز کردن قفل\u200cهای درب، تعویض و تعمیر قفل، و نصب انواع قفل ایمنی است. این سرویس به\u200cصورت فوری و در محل ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/19.jpg", BasePrice = 100000 },
                new AcharDomainCore.Entites.HomeService { Id = 20, Title = "نصب و تعمیرات شیرالات", SubCategoryId = 6, IsDeleted = false, 
                    Description = "سرویس نصب و تعمیرات شیرآلات شامل نصب انواع شیرآلات بهداشتی، تعویض واشر و کارتریج، رفع نشتی و تنظیم فشار آب است. این سرویس برای بهبود عملکرد و افزایش دوام سیستم لوله\u200cکشی ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/20.jpg", BasePrice = 150000 },
                new AcharDomainCore.Entites.HomeService { Id = 21, Title = "تخلیه چاه ولوله باز کنی", SubCategoryId = 6, IsDeleted = false,
                    Description = "سرویس تخلیه چاه و لوله\u200cبازکنی شامل رفع گرفتگی لوله\u200cها، تخلیه چاه\u200cهای فاضلاب، رسوب\u200cزدایی و رفع بوی نامطبوع با استفاده از تجهیزات تخصصی است. این سرویس به بهبود عملکرد سیستم فاضلاب و جلوگیری از مشکلات جدی کمک می\u200cکند.", 
                    ImageSrc = "/assets/img/homeservice/21.jpg", BasePrice = 150000 },
                new AcharDomainCore.Entites.HomeService { Id = 22, Title = "پمپ و منبع اب", SubCategoryId = 6, IsDeleted = false, 
                    Description = "سرویس پمپ و منبع آب شامل نصب، تعمیر و سرویس انواع پمپ\u200cهای آب، تنظیم فشار، هواگیری و عیب\u200cیابی مخازن آب است. این سرویس برای افزایش راندمان سیستم آبرسانی و جلوگیری از افت فشار ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/22.jpg", BasePrice = 250000 },
                new AcharDomainCore.Entites.HomeService { Id = 23, Title = "تشخیص و ترمیم ترکیدگی لوله", SubCategoryId = 6, IsDeleted = false,
                    Description = "سرویس تشخیص و ترمیم ترکیدگی لوله شامل شناسایی محل نشتی با دستگاه\u200cهای دقیق، تعمیر یا تعویض لوله\u200cهای آسیب\u200cدیده و جلوگیری از هدررفت آب است. این سرویس برای حفظ سلامت سیستم لوله\u200cکشی و کاهش هزینه\u200cهای ناشی از نشتی ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/23.jpg", BasePrice = 100000 },
                new AcharDomainCore.Entites.HomeService { Id = 24, Title = "لوله کشی گاز", SubCategoryId = 6, IsDeleted = false,
                    Description = "سرویس لوله\u200cکشی گاز شامل طراحی، نصب، تعمیر و تست ایمنی لوله\u200cهای گاز در ساختمان\u200cهای مسکونی و تجاری است. این سرویس با رعایت استانداردهای ایمنی برای تأمین گاز مطمئن و پایدار ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/24.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 25, Title = "نصب و تعمیر سینک ظرفشویی", SubCategoryId = 7, IsDeleted = false,
                    Description = "سرویس نصب و تعمیر سینک ظرفشویی شامل نصب انواع سینک، تعویض اتصالات، رفع نشتی، تنظیم شیب فاضلاب و آب\u200cبندی صحیح است. این سرویس برای بهبود عملکرد و جلوگیری از مشکلات نشتی و گرفتگی ارائه می\u200cشود."
                    , ImageSrc = "/assets/img/homeservice/25.jpg", BasePrice = 400000 },
                new AcharDomainCore.Entites.HomeService { Id = 26, Title = "سیم کشی و کابل کشی", SubCategoryId = 8, IsDeleted = false,
                    Description = "سرویس سیم\u200cکشی و کابل\u200cکشی شامل طراحی، اجرا، تعمیر و ارتقای سیستم\u200cهای برق\u200cرسانی در ساختمان\u200cهای مسکونی، اداری و صنعتی است. این سرویس با رعایت استانداردهای ایمنی برای تأمین برق پایدار و مطمئن ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/26.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 27, Title = "رفع اتصالی", SubCategoryId = 8, IsDeleted = false,
                    Description = "سرویس رفع اتصالی شامل شناسایی و تعمیر اتصالات برق معیوب، بررسی سیستم\u200cهای برقی، تعویض فیوزها و سیم\u200cهای آسیب\u200cدیده است. این سرویس برای جلوگیری از خطرات برقی و بهبود عملکرد سیستم برق\u200cرسانی ارائه می\u200cشود.\n\n\n\n\n\n\n\n",
                    ImageSrc = "/assets/img/homeservice/27.jpg", BasePrice = 100000 },
                new AcharDomainCore.Entites.HomeService { Id = 28, Title = "نصب و تعمیر ایفون", SubCategoryId = 8, IsDeleted = false, 
                    Description = "سرویس نصب و تعمیر آیفون شامل نصب سیستم\u200cهای آیفون صوتی و تصویری، تعمیر و رفع مشکلات مربوط به صدا، تصویر، دکمه\u200cها و اتصالات است. این سرویس برای بهبود عملکرد و افزایش امنیت ساختمان\u200cها ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/28.jpg", BasePrice = 150000 },
                new AcharDomainCore.Entites.HomeService { Id = 29, Title = "نصب لوستروچراغ", SubCategoryId = 8, IsDeleted = false,
                    Description = "سرویس نصب لوستر و چراغ شامل نصب انواع لوسترها و چراغ\u200cهای تزئینی، تنظیم ارتفاع و بررسی اتصالات برقی است. این سرویس برای روشنایی و زیباسازی فضاهای داخلی منازل و ادارات ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/29.jpg", BasePrice = 150000 },
                new AcharDomainCore.Entites.HomeService { Id = 30, Title = "کلید و پریز", SubCategoryId = 8, IsDeleted = false,
                    Description = "سرویس نصب و تعمیر کلید و پریز شامل نصب انواع کلید و پریز برق، تعویض قطعات فرسوده، رفع اتصالات معیوب و بررسی ایمنی سیستم برق است. این سرویس برای بهبود عملکرد و ایمنی سیستم\u200cهای برقی در ساختمان\u200cها ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/30.jpg", BasePrice = 100000 },
                new AcharDomainCore.Entites.HomeService { Id = 31, Title = "نصب و تعویض فیوز", SubCategoryId = 8, IsDeleted = false,
                    Description = "سرویس نصب و تعویض فیوز شامل بررسی سیستم برق\u200cرسانی، تعویض فیوزهای سوخته یا معیوب و تنظیم ایمنی مدارهای برقی است. این سرویس برای جلوگیری از بروز مشکلات برقی و حفظ امنیت ساختمان ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/31.jpg", BasePrice = 100000 },
                new AcharDomainCore.Entites.HomeService { Id = 32, Title = "تعمیر و سرویس اسانسور", SubCategoryId =8, IsDeleted = false, 
                    Description = "سرویس تعمیر و نگهداری آسانسور شامل بررسی و تعمیر سیستم\u200cهای مکانیکی، الکتریکی و ایمنی آسانسور، تنظیم درب\u200cها، روغن\u200cکاری قطعات و رفع مشکلات عملکردی است. این سرویس برای افزایش عمر مفید و بهبود عملکرد آسانسور ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/32.jpg", BasePrice = 400000 },
                new AcharDomainCore.Entites.HomeService { Id = 33, Title = "نصب سنسور تایمر", SubCategoryId = 8, IsDeleted = false,
                    Description = "سرویس نصب سنسور تایمر شامل نصب سنسورهای حرکتی یا نور برای روشن و خاموش کردن اتوماتیک لوازم برقی مانند چراغ\u200cها یا فن\u200cها است. این سرویس به صرفه\u200cجویی در مصرف انرژی و افزایش راحتی در فضاهای مختلف کمک می\u200cکند.", 
                    ImageSrc = "/assets/img/homeservice/33.jpg", BasePrice = 100 },
                new AcharDomainCore.Entites.HomeService { Id = 34, Title = "ساخت کابینت وکمددیواری", SubCategoryId = 9, IsDeleted = false,
                    Description = "سرویس ساخت کابینت و کمد دیواری شامل طراحی، ساخت و نصب انواع کابینت آشپزخانه، کمد دیواری و سیستم\u200cهای ذخیره\u200cسازی سفارشی است. این سرویس برای بهینه\u200cسازی فضای داخلی و ایجاد دکوراسیون مرتب و کاربردی ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/34.jpg", BasePrice = 4000000 },
                new AcharDomainCore.Entites.HomeService { Id = 35, Title = "نجاری", SubCategoryId = 9, IsDeleted = false, 
                    Description = "سرویس نجاری شامل ساخت، تعمیر و نصب انواع مبلمان چوبی، درب و پنجره، قفسه\u200cها و سایر وسایل چوبی است. این سرویس برای ایجاد دکوراسیون چوبی زیبا و مقاوم در فضاهای مسکونی و اداری ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/35.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 36, Title = "تعمیرات مبلمان", SubCategoryId = 9, IsDeleted = false, 
                    Description = "سرویس تعمیرات مبلمان شامل تعمیر، بازسازی و نوسازی انواع مبلمان چوبی و پارچه\u200cای، تعویض پارچه، فوم، و تعمیر اسکلت و پایه\u200cها است. این سرویس به حفظ زیبایی و دوام مبلمان کمک می\u200cکند.",
                    ImageSrc = "/assets/img/homeservice/36.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 37, Title = "خدمات درب چوبی و ضد سرقت", SubCategoryId = 9, IsDeleted = false,
                    Description = "سرویس خدمات درب چوبی و ضد سرقت شامل نصب، تعمیر، تعویض یراق\u200cآلات، تنظیم درب\u200cها، و بررسی ایمنی است. این سرویس برای افزایش امنیت و زیبایی درب\u200cهای ورودی ساختمان\u200cها ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/37.jpg", BasePrice = 2500000 },
                new AcharDomainCore.Entites.HomeService { Id = 38, Title = "پارتیشن شیشه ای", SubCategoryId = 10, IsDeleted = false,
                    Description = "سرویس نصب پارتیشن شیشه\u200cای شامل طراحی، اندازه\u200cگیری، برش و نصب پارتیشن\u200cهای شیشه\u200cای برای تقسیم\u200cبندی فضاهای داخلی است. این سرویس برای ایجاد فضای جداگانه و زیبا با نوردهی مناسب در ادارات و محیط\u200cهای تجاری ارائه می\u200cشود.\n\n\n\n\n\n\n\n",
                    ImageSrc = "/assets/img/homeservice/38.jpg", BasePrice = 2500000 },
                new AcharDomainCore.Entites.HomeService { Id = 39, Title = "شیشه بری و اینه کاری", SubCategoryId = 10, IsDeleted = false,
                    Description = "سرویس شیشه\u200cبری و آینه\u200cکاری شامل برش دقیق انواع شیشه\u200cها و آینه\u200cها، نصب و چسباندن آن\u200cها در فضاهای مختلف مانند پنجره\u200cها، درب\u200cها، دیوارها و دکورهای داخلی است. این سرویس برای زیباسازی و تأمین نیازهای شیشه\u200cای و آینه\u200cای در ساختمان\u200cها ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/39.jpg", BasePrice = 1500000 },
                new AcharDomainCore.Entites.HomeService { Id = 40, Title = "شیشه ریلی اسلاید", SubCategoryId = 10, IsDeleted = false,
                    Description = "سرویس نصب شیشه ریلی اسلاید شامل طراحی، برش و نصب شیشه\u200cهای ریلی متحرک برای فضاهایی مانند درب\u200cهای ورودی، پارتیشن\u200cها و فضاهای تجاری است. این سرویس برای استفاده بهینه از فضا و ایجاد ظاهری مدرن و شیک ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/40.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 41, Title = "تعمیرونگهداری موتور خانه", SubCategoryId = 11, IsDeleted = false, 
                    Description = "سرویس تعمیر و نگهداری موتورخانه شامل بررسی و تعمیر سیستم\u200cهای گرمایشی و سرمایشی مانند پکیج\u200cها، بویلرها، پمپ\u200cها و سیستم\u200cهای لوله\u200cکشی است. این سرویس برای بهبود عملکرد، افزایش بهره\u200cوری و جلوگیری از مشکلات احتمالی در موتورخانه ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/41.jpg", BasePrice = 3000000 },
                new AcharDomainCore.Entites.HomeService { Id = 42, Title = "سرویس و تعمیر چیلر", SubCategoryId = 11, IsDeleted = false,
                    Description = "سرویس و تعمیر چیلر شامل عیب\u200cیابی و تعمیر کمپرسور، تمیز کردن فیلترها، بررسی و تنظیم سیستم\u200cهای گاز، شارژ گاز و عایق\u200cکاری لوله\u200cها است. این سرویس برای بهبود عملکرد و افزایش طول عمر چیلرها در سیستم\u200cهای تهویه مطبوع تجاری و صنعتی ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/42.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 43, Title = "نصب و تعمیر یخچال وفریز", SubCategoryId = 11, IsDeleted = false,
                    Description = "سرویس نصب و تعمیر یخچال و فریزر شامل نصب دستگاه، عیب\u200cیابی، تعمیر کمپرسور، تعویض قطعات معیوب، شارژ گاز و تنظیم دما است. این سرویس برای بهبود عملکرد و طول عمر یخچال و فریزر در منازل و محیط\u200cهای تجاری ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/43.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 44, Title = "نصب و تعمیر ماشین لباسشویی", SubCategoryId = 11, IsDeleted = false,
                    Description = "سرویس نصب و تعمیر ماشین لباسشویی شامل نصب دستگاه، بررسی و رفع مشکلات مربوط به موتور، پمپ آب، برد الکترونیکی، تعویض قطعات معیوب و تعمیر نشت آب است. این سرویس برای بهبود عملکرد و طول عمر ماشین لباسشویی در خانه\u200cها و محیط\u200cهای تجاری ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/44.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 45, Title = "نصب و تعمیرماشین ظرفشویی", SubCategoryId = 11, IsDeleted = false, 
                    Description = "سرویس نصب و تعمیر ماشین ظرفشویی شامل نصب دستگاه، عیب\u200cیابی و تعمیر مشکلات مربوط به موتور، پمپ آب، فیلترها، برد الکترونیکی و رفع نشت آب است. این سرویس برای بهبود عملکرد و افزایش عمر مفید ماشین ظرفشویی در منازل و محیط\u200cهای تجاری ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/45.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 46, Title = "تعمیر جاروبرقی", SubCategoryId = 11, IsDeleted = false,
                    Description = "سرویس تعمیر جاروبرقی شامل عیب\u200cیابی و تعمیر موتور، تعویض قطعات معیوب مانند فیلتر، لوله و برس\u200cها، رفع مشکلات مکش و بررسی سیم برق است. این سرویس برای بهبود عملکرد و افزایش عمر مفید جاروبرقی در منازل و محیط\u200cهای تجاری ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/46.jpg", BasePrice = 500000 },
                new AcharDomainCore.Entites.HomeService { Id = 47, Title = "تعمیر کامپیوتر و لپ تاپ", SubCategoryId = 12, IsDeleted = false, 
                    Description = "سرویس تعمیر کامپیوتر و لپ\u200cتاپ شامل عیب\u200cیابی و تعمیر مشکلات سخت\u200cافزاری و نرم\u200cافزاری، تعویض قطعات معیوب، نصب سیستم\u200cعامل، به\u200cروزرسانی نرم\u200cافزارها و رفع مشکلات مربوط به عملکرد سیستم است. این سرویس برای بهبود عملکرد و افزایش طول عمر دستگاه\u200cها ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/47.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 48, Title = "تعمیر ماشین های اداری", SubCategoryId = 12, IsDeleted = false,
                    Description = "سرویس تعمیر ماشین\u200cهای اداری شامل تعمیر و نگهداری دستگاه\u200cهایی مانند پرینتر، اسکنر، فکس و کپی است. این سرویس شامل عیب\u200cیابی، تعویض قطعات معیوب، تعمیر مکانیزم\u200cهای داخلی و به\u200cروزرسانی نرم\u200cافزارها برای بهبود عملکرد دستگاه\u200cها ارائه می\u200cشود.\n\n\n\n\n\n\n\n",
                    ImageSrc = "/assets/img/homeservice/48.jpg", BasePrice = 1500000 },
                new AcharDomainCore.Entites.HomeService { Id = 49, Title = "مودم واینترنت", SubCategoryId = 12, IsDeleted = false,
                    Description = "سرویس نصب و تعمیر مودم و اینترنت شامل راه\u200cاندازی مودم، تنظیمات شبکه، بررسی سرعت اینترنت، رفع مشکلات اتصال و عیب\u200cیابی کابل\u200cها و اتصالات است. این سرویس برای بهبود عملکرد اینترنت و رفع مشکلات شبکه در منازل و محیط\u200cهای تجاری ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/49.jpg", BasePrice = 500000 },
                new AcharDomainCore.Entites.HomeService { Id = 50, Title = "خدمات تاچ و ال سی دی", SubCategoryId = 13, IsDeleted = false,
                    Description = "سرویس خدمات تاچ و ال سی دی شامل تعمیر یا تعویض صفحه نمایش لمسی و ال سی دی در دستگاه\u200cهایی مانند گوشی\u200cهای موبایل، تبلت\u200cها و لپ\u200cتاپ\u200cها است. این سرویس برای رفع مشکلات صفحه نمایش، از جمله ترک\u200cخوردگی، رنگ\u200cپریدگی یا نواقص لمسی ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/50.jpg", BasePrice = 1500000 },
                new AcharDomainCore.Entites.HomeService { Id = 51, Title = " خدمات باتری موبایل", SubCategoryId = 13, IsDeleted = false, 
                    Description = "سرویس خدمات باتری موبایل شامل تعویض باتری معیوب، بررسی عملکرد باتری، کالیبراسیون و رفع مشکلات شارژ در دستگاه\u200cهای موبایل است. این سرویس برای بهبود عمر باتری و عملکرد دستگاه\u200cهای موبایل ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/51.jpg", BasePrice = 300000},
                new AcharDomainCore.Entites.HomeService { Id = 52, Title = "خدمات نرم افزاری", SubCategoryId = 13, IsDeleted = false,
                    Description = "سرویس خدمات نرم\u200cافزاری شامل نصب، به\u200cروزرسانی، پشتیبانی و رفع مشکلات نرم\u200cافزاری در سیستم\u200cهای مختلف، از جمله نصب سیستم\u200cعامل، برنامه\u200cها و ابزارهای کاربردی است. این سرویس برای بهبود عملکرد و رفع اشکالات نرم\u200cافزاری در دستگاه\u200cهای مختلف ارائه می\u200cشود.\n\n\n\n\n\n\n\n",
                    ImageSrc = "/assets/img/homeservice/52.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 53, Title = " اسباب کشی با خاور و کامیون", SubCategoryId = 14, IsDeleted = false,
                    Description = "سرویس اسباب\u200cکشی با خاور و کامیون شامل حمل و نقل اثاثیه منزل یا اداری با استفاده از وسایل نقلیه بزرگ و مناسب، بسته\u200cبندی ایمن، بارگیری، تخلیه و انتقال به مقصد است. این سرویس برای راحتی و امنیت در جابجایی اثاثیه ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/53.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 54, Title = "اسباب کشی با وانت و نیسان", SubCategoryId = 14, IsDeleted = false, 
                    Description = "سرویس اسباب\u200cکشی با وانت و نیسان شامل حمل و نقل اثاثیه کوچک و متوسط با استفاده از خودروهای مناسب برای جابجایی سریع و ایمن است. این سرویس برای انتقال اثاثیه از منزل یا دفتر به مقصد با هزینه مناسب و سرعت بالا ارائه می\u200cشود.\n\n\n\n\n\n\n\n",
                    ImageSrc = "/assets/img/homeservice/54.jpg", BasePrice = 1500000 },
                new AcharDomainCore.Entites.HomeService { Id = 55, Title = "سرویس بسته بندی", SubCategoryId = 14, IsDeleted = false,
                    Description = "سرویس بسته\u200cبندی شامل بسته\u200cبندی ایمن و مطمئن اثاثیه و کالاها با استفاده از مواد محافظ مانند فوم، کارتن، نوار چسب و پلاستیک حبابدار است. این سرویس برای جلوگیری از آسیب\u200cدیدگی در حین حمل\u200cونقل و جابجایی اثاثیه ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/55.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 56, Title = "اسباب کشی شرکت ها و سازمان ها", SubCategoryId = 14, IsDeleted = false,
                    Description = "سرویس اسباب\u200cکشی شرکت\u200cها و سازمان\u200cها شامل جابجایی اثاثیه اداری، مبلمان، تجهیزات کامپیوتری و اسناد با استفاده از وسایل نقلیه مناسب و بسته\u200cبندی ایمن است. این سرویس برای انتقال راحت و بدون دردسر شرکت\u200cها و سازمان\u200cها به محل جدید ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/56.jpg", BasePrice = 300000 },
                new AcharDomainCore.Entites.HomeService { Id = 57, Title = "تعویض باتری خودرو", SubCategoryId = 15, IsDeleted = false, 
                    Description = "سرویس تعویض باتری خودرو شامل بررسی وضعیت باتری، تعویض باتری فرسوده با باتری جدید و انجام تست\u200cهای لازم برای اطمینان از عملکرد صحیح سیستم برق\u200cرسانی خودرو است. این سرویس برای حفظ عملکرد بهینه خودرو و جلوگیری از مشکلات ناشی از خرابی باتری ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/57.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 58, Title = "باتری ب باتری", SubCategoryId = 15, IsDeleted = false,
                    Description = "سرویس باتری به باتری شامل کمک به خودروهایی است که باتری آن\u200cها خالی یا خراب شده است. در این سرویس، باتری سالم از یک خودرو به خودرو دیگر منتقل می\u200cشود تا آن را روشن کرده و مشکل باتری خودرو رفع شود. این سرویس در مواقع اضطراری برای شروع حرکت خودرو ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/58.jpg", BasePrice = 500000 },
                new AcharDomainCore.Entites.HomeService { Id = 59, Title = "مکانیکی خودرو", SubCategoryId = 15, IsDeleted = false, 
                    Description = "سرویس مکانیکی خودرو شامل تعمیرات و نگهداری سیستم\u200cهای مختلف خودرو، از جمله موتور، ترمزها، سیستم تعلیق، اگزوز، و انتقال نیرو است. این سرویس برای رفع مشکلات فنی و بهبود عملکرد خودرو ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/59.jpg", BasePrice = 3000000 },
                new AcharDomainCore.Entites.HomeService { Id = 60, Title = "کارشناسی خودرو", SubCategoryId = 15, IsDeleted = false,
                    Description = "سرویس کارشناسی خودرو شامل بررسی دقیق وضعیت فنی و ظاهری خودرو قبل از خرید یا فروش، از جمله بررسی موتور، سیستم ترمز، بدنه، شاسی، سیستم تعلیق، و تشخیص مشکلات مخفی است. این سرویس برای اطمینان از سلامت خودرو و جلوگیری از خرید یا فروش خودرو با مشکلات پنهان ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/60.jpg", BasePrice = 2500000 },
                new AcharDomainCore.Entites.HomeService { Id = 61, Title = "تعویض لاستیک", SubCategoryId = 15, IsDeleted = false,
                    Description = "سرویس تعویض لاستیک شامل جابجایی لاستیک\u200cهای فرسوده یا آسیب\u200cدیده با لاستیک\u200cهای جدید، بررسی وضعیت تایرها، و تنظیم فشار باد لاستیک\u200cها است. این سرویس برای حفظ ایمنی و بهبود عملکرد خودرو در جاده\u200cها ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/61.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 62, Title = "تعویض لنت", SubCategoryId = 15, IsDeleted = false, 
                    Description = "سرویس تعویض لنت شامل بررسی وضعیت لنت\u200cهای ترمز، تعویض لنت\u200cهای فرسوده با لنت\u200cهای جدید، و تنظیم سیستم ترمز برای بهبود عملکرد آن است. این سرویس برای افزایش ایمنی خودرو و بهبود عملکرد ترمزها ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/62.jpg", BasePrice = 500000 },
                new AcharDomainCore.Entites.HomeService { Id = 63, Title = "تعویض روغن", SubCategoryId = 15, IsDeleted = false,
                    Description = "سرویس تعویض روغن شامل تخلیه روغن قدیمی موتور، تعویض فیلتر روغن و افزودن روغن جدید به موتور است. این سرویس برای حفظ عملکرد بهینه موتور، کاهش سایش و افزایش طول عمر آن ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/63.jpg", BasePrice = 600000 },
                new AcharDomainCore.Entites.HomeService { Id = 64, Title = "سرویس دوره ای گیربکس اتوماتیک", SubCategoryId = 15, IsDeleted = false, 
                    Description = "سرویس دوره\u200cای گیربکس اتوماتیک شامل بررسی و تعویض روغن گیربکس، تنظیم و بازبینی سیستم انتقال قدرت، و اطمینان از عملکرد صحیح قطعات داخلی گیربکس است. این سرویس برای حفظ عملکرد بهینه گیربکس، جلوگیری از مشکلات فنی و افزایش طول عمر سیستم انتقال قدرت خودرو ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/64.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 65, Title = "سرامیک خودرو", SubCategoryId = 16, IsDeleted = false,
                    Description = "سرویس سرامیک خودرو شامل اعمال پوشش نانو سرامیک بر روی بدنه خودرو است که به منظور حفاظت از رنگ و سطح خودرو در برابر خراش\u200cها، لکه\u200cها، آلودگی\u200cها و اشعه UV انجام می\u200cشود. این پوشش باعث براقیت بیشتر، دوام بیشتر و سهولت در تمیز کردن سطح خودرو می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/65.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 66, Title = "کارواش نانو", SubCategoryId = 16, IsDeleted = false,
                    Description = "سرویس کارواش نانو شامل شستشوی خودرو با استفاده از محصولات نانو تکنولوژی است که به طور مؤثری آلودگی\u200cها، گرد و غبار، و لکه\u200cها را از بین می\u200cبرد. این روش شستشو به سطح خودرو لایه\u200cای محافظتی می\u200cدهد که باعث حفظ براقیت رنگ و جلوگیری از ایجاد لکه\u200cهای جدید می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/66.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 67, Title = "کارواش با اب", SubCategoryId = 16, IsDeleted = false,
                    Description = "سرویس کارواش با آب شامل شستشوی خودرو با استفاده از آب و مواد شوینده مخصوص است که به طور مؤثر خاک، کثیفی و لکه\u200cها را از بدنه، چرخ\u200cها و شیشه\u200cها پاک می\u200cکند. این روش شستشو برای تمیز کردن کامل خودرو و حفظ ظاهر آن در شرایط عادی ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/67.jpg", BasePrice = 700000 },
                new AcharDomainCore.Entites.HomeService { Id = 68, Title = "موتورشویی خودرو", SubCategoryId = 16, IsDeleted = false,
                    Description = "سرویس موتورشویی خودرو شامل تمیز کردن و شستشوی موتور خودرو با استفاده از مواد شوینده مخصوص است. این سرویس به پاک\u200cسازی روغن، کثیفی و گرد و غبار از بخش\u200cهای مختلف موتور کمک کرده و باعث بهبود عملکرد و جلوگیری از آسیب به قطعات می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/68.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 69, Title = "نصب شیشه دودی درمحل", SubCategoryId = 16, IsDeleted = false,
                    Description = "سرویس نصب شیشه دودی در محل شامل نصب فیلترهای دودی بر روی شیشه\u200cهای خودرو یا ساختمان است. این سرویس به منظور کاهش تابش نور خورشید، حفظ حریم خصوصی، و جلوگیری از افزایش دمای داخل خودرو یا فضا ارائه می\u200cشود. شیشه دودی همچنین به محافظت از مواد داخلی در برابر اشعه UV کمک می\u200cکند.",
                    ImageSrc = "/assets/img/homeservice/69.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 70, Title = "خدمات ناخن", SubCategoryId = 17, IsDeleted = false,
                    Description = "سرویس خدمات ناخن شامل انجام انواع خدمات مراقبت و زیبایی ناخن\u200cها از جمله مانیکور، پدیکور، کاشت ناخن، ترمیم ناخن، طراحی و لاک زدن است. این سرویس برای تقویت، بهبود ظاهر و زیباسازی ناخن\u200cها ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/70.jpg", BasePrice = 500000 },
                new AcharDomainCore.Entites.HomeService { Id = 71, Title = "رنگ مو بانوان", SubCategoryId = 17, IsDeleted = false,
                    Description = "سرویس رنگ مو بانوان شامل انتخاب و اعمال رنگ مو بر اساس سلیقه مشتری، از جمله رنگ\u200cهای طبیعی یا فانتزی، با استفاده از رنگ\u200cهای حرفه\u200cای و ماندگار است. این سرویس برای تغییر رنگ، پوشاندن موهای سفید یا ایجاد جلوه\u200cای جدید و زیبا بر روی موهای بانوان ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/71.jpg", BasePrice = 600000 },
                new AcharDomainCore.Entites.HomeService { Id = 72, Title = "کوتاهی مو بانوان", SubCategoryId = 17, IsDeleted = false,
                    Description = "سرویس کوتاهی مو بانوان شامل اصلاح و کوتاه کردن موها با توجه به سلیقه مشتری و مدل\u200cهای روز است. این سرویس برای ایجاد تغییرات ظاهری، رفع موهای آسیب\u200cدیده و فرم\u200cدهی به موها برای ظاهر مرتب و شیک ارائه می\u200cشود.", 
                    ImageSrc = "/assets/img/homeservice/72.jpg", BasePrice = 700000 },
                new AcharDomainCore.Entites.HomeService { Id = 73, Title = "کراتینه و ویتامینه مو بانوان", SubCategoryId = 17, IsDeleted = false, 
                    Description = "سرویس کراتینه و ویتامینه مو بانوان شامل درمان و بازسازی موهای آسیب\u200cدیده با استفاده از مواد کراتینه و ویتامین\u200cهای مغذی است. این سرویس باعث نرمی، درخشندگی و سلامت موها می\u200cشود و همچنین به کاهش وز و آسیب\u200cهای ناشی از استفاده زیاد از ابزارهای حرارتی کمک می\u200cکند.", 
                    ImageSrc = "/assets/img/homeservice/73.jpg", BasePrice = 100000 },
                new AcharDomainCore.Entites.HomeService { Id = 74, Title = "بافت مو بانوان", SubCategoryId = 17, IsDeleted = false, 
                    Description = "سرویس بافت مو بانوان شامل انواع مدل\u200cهای بافت مو مانند بافت ساده، فانتزی، فرانسوی یا آفریقایی است که به موها ظاهری خاص و زیبا می\u200cدهد. این سرویس برای ایجاد مدل\u200cهای متفاوت و جذاب برای مناسبت\u200cها یا استفاده روزانه ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/74.jpg", BasePrice = 800000 },
                new AcharDomainCore.Entites.HomeService { Id = 75, Title = "مراقلت و نگهداری", SubCategoryId = 18, IsDeleted = false,
                    Description = "سرویس مراقبت و نگهداری از سالمندان، کودکان و بیماران شامل ارائه خدمات بهداشتی، مراقبتی و رفاهی به افراد نیازمند مراقبت است. این سرویس ممکن است شامل کمک در انجام فعالیت\u200cهای روزمره، نظافت، مصرف داروها، همراهی در مراجعه به پزشک، و فراهم کردن محیطی امن و راحت برای این افراد باشد.",
                    ImageSrc = "/assets/img/homeservice/75.jpg", BasePrice = 800000 },
                new AcharDomainCore.Entites.HomeService { Id = 76, Title = "پرستاری و تزریقات", SubCategoryId = 18, IsDeleted = false,
                    Description = "سرویس پرستاری و تزریقات شامل ارائه خدمات بهداشتی و پزشکی در منزل است که شامل تزریق داروها، خون\u200cگیری، پانسمان، و سایر خدمات مراقبتی و پرستاری می\u200cشود. این سرویس برای افرادی که نیاز به مراقبت\u200cهای پزشکی مداوم دارند یا نمی\u200cتوانند به مراکز درمانی مراجعه کنند، ارائه می\u200cشود.",
                    ImageSrc = "/assets/img/homeservice/76.jpg", BasePrice = 800000 },
                new AcharDomainCore.Entites.HomeService { Id = 77, Title = "معاینه پزشکی", SubCategoryId = 18, IsDeleted = false,
                    Description = "سرویس معاینه پزشکی شامل ارزیابی و بررسی سلامت عمومی فرد توسط پزشک است. این معاینه می\u200cتواند شامل بررسی علائم بیماری، آزمایشات فیزیکی، مشاوره درباره سبک زندگی و تجویز درمان\u200cهای مورد نیاز باشد. هدف این سرویس پیشگیری از بیماری\u200cها و تشخیص زودهنگام مشکلات بهداشتی است.",
                    ImageSrc = "/assets/img/homeservice/77.jpg", BasePrice = 500000 },
                new AcharDomainCore.Entites.HomeService { Id = 78, Title = "خدمات دامپزشکی در محل", SubCategoryId = 19, IsDeleted = false,
                    Description = "سرویس خدمات دامپزشکی در محل شامل ارائه مراقبت\u200cهای پزشکی و درمانی برای حیوانات خانگی یا دام\u200cها در محل زندگی یا مزرعه است. این خدمات می\u200cتواند شامل معاینه، درمان بیماری\u200cها، واکسیناسیون، دارودرمانی و جراحی\u200cهای جزئی باشد. هدف این سرویس فراهم آوردن راحتی برای صاحب حیوانات و ارائه خدمات بهداشتی بدون نیاز به مراجعه به کلینیک دامپزشکی است.",
                    ImageSrc = "/assets/img/homeservice/78.jpg", BasePrice = 400000 },
                new AcharDomainCore.Entites.HomeService { Id = 79, Title = "خدمات تربیت حیوانات خانگی", SubCategoryId = 19, IsDeleted = false,
                    Description = "سرویس خدمات تربیت حیوانات خانگی شامل آموزش و تربیت حیوانات مانند سگ\u200cها و گربه\u200cها برای رفتارهای خاص یا رفع مشکلات رفتاری است. این خدمات ممکن است شامل آموزش فرمان\u200cهای ساده، اصلاح رفتارهای نامطلوب، اجتماعی\u200cسازی حیوان و ایجاد عادات مناسب برای تعامل با انسان\u200cها و سایر حیوانات باشد. هدف این سرویس، بهبود ارتباط صاحب حیوان با حیوان خانگی و فراهم آوردن محیطی سالم و هماهنگ است.",
                    ImageSrc = "/assets/img/homeservice/79.jpg", BasePrice = 300000 },
                new AcharDomainCore.Entites.HomeService { Id = 80, Title = "خدمات شست وشو ارایشی حیوانات خانگی", SubCategoryId = 19, IsDeleted = false,
                    Description = "سرویس شستشو و آرایش حیوانات خانگی شامل تمیز کردن، شستشو، و مرتب\u200cسازی موهای حیوانات خانگی است. این خدمات ممکن است شامل حمام، شستشوی مو، کوتاهی و اصلاح مو، شانه کردن، و استفاده از محصولات بهداشتی مخصوص حیوانات باشد. هدف این سرویس، بهبود بهداشت و ظاهر حیوانات خانگی و فراهم آوردن راحتی و سلامت برای آنها است.",
                    ImageSrc = "/assets/img/homeservice/80.jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 81, Title = "مشاورمالی و مالیاتی", SubCategoryId = 20, IsDeleted = false, 
                    Description = "سرویس مشاور مالی و مالیاتی شامل ارائه مشاوره تخصصی در زمینه مدیریت مالی، برنامه\u200cریزی مالی، و مسائل مالیاتی است. این خدمات می\u200cتواند شامل کمک به تنظیم مالیات، کاهش هزینه\u200cها، بهینه\u200cسازی سرمایه\u200cگذاری\u200cها و برنامه\u200cریزی برای آینده مالی باشد. مشاوران مالی و مالیاتی به افراد و کسب\u200cوکارها کمک می\u200cکنند تا تصمیمات مالی بهینه و مطابق با قوانین مالیاتی اتخاذ کنند.\n\n\n\n\n\n\n\n",
                    ImageSrc = "/assets/img/homeservice/81.jpg", BasePrice = 300000 },
                new AcharDomainCore.Entites.HomeService { Id = 82, Title = "کوتاهی موی سر و اصلاح صورت", SubCategoryId = 21, IsDeleted = false, 
                    Description = "سرویس کوتاهی موی سر و اصلاح صورت مردانه شامل اصلاح و کوتاه کردن موهای سر به مدل\u200cهای متنوع و مطابق با سلیقه مشتری، و همچنین اصلاح صورت با استفاده از تیغ، ماشین ریش\u200cزنی و سایر ابزارهای حرفه\u200cای است. این سرویس برای ایجاد ظاهری مرتب، شیک و جذاب برای مردان طراحی شده و می\u200cتواند شامل اصلاح ریش، سبیل و طراحی خط\u200cهای صورت باشد.",
                    ImageSrc = "/assets/img/homeservice/82jpg", BasePrice = 200000 },
                new AcharDomainCore.Entites.HomeService { Id = 83, Title = "گریم داماد", SubCategoryId = 21, IsDeleted = false,
                    Description = "سرویس گریم داماد شامل آرایش و زیباسازی چهره داماد برای روز عروسی است. این سرویس شامل استفاده از محصولات آرایشی مخصوص برای بهبود پوست، پوشاندن عیوب صورت، ایجاد جلوه\u200cای طبیعی و زیبا، و تنظیم جزئیات چهره برای عکاسی و فیلمبرداری است. هدف این سرویس کمک به داماد برای داشتن ظاهری مرتب، جذاب و اعتماد به نفس بالا در روز مهم زندگی\u200cاش است.",
                    ImageSrc = "/assets/img/homeservice/83.jpg", BasePrice = 400000 },
                new AcharDomainCore.Entites.HomeService { Id = 84, Title = "برنامه ورزشی و تغذیه", SubCategoryId = 22, IsDeleted = false, 
                    Description = "سرویس برنامه ورزشی و تغذیه شامل ارائه برنامه\u200cهای تمرینی و رژیم\u200cهای غذایی متناسب با اهداف فردی مانند کاهش وزن، افزایش عضله، بهبود سلامت عمومی یا افزایش استقامت است. این برنامه\u200cها بر اساس وضعیت بدنی، نیازها و سبک زندگی فرد طراحی می\u200cشود و ممکن است شامل تمرینات قدرتی، هوازی، انعطاف\u200cپذیری و تغذیه سالم با توجه به نیازهای تغذیه\u200cای خاص هر شخص باشد. هدف این سرویس کمک به فرد برای رسیدن به اهداف ورزشی و بدنی خود به صورت مؤثر و سالم است.",
                    ImageSrc = "/assets/img/homeservice/84.jpg", BasePrice = 1000000 },
                new AcharDomainCore.Entites.HomeService { Id = 85, Title = "کلاس یوگا در خانه", SubCategoryId = 22, IsDeleted = false,
                    Description = "سرویس کلاس یوگا در خانه شامل برگزاری جلسات یوگا با مربی مجرب در منزل شما است. این کلاس\u200cها می\u200cتواند شامل تمرینات تنفسی، انعطاف\u200cپذیری، تقویت عضلات، و مدیتیشن باشد و به بهبود سلامت جسمی و روانی کمک کند. کلاس\u200cهای یوگا در خانه برای افرادی که وقت یا تمایل به رفتن به باشگاه ندارند، گزینه\u200cای راحت و شخصی است.",
                    ImageSrc = "/assets/img/homeservice/85.jpg", BasePrice = 2000000},
                new AcharDomainCore.Entites.HomeService { Id = 86, Title = "کلاس فیتنس در خانه", SubCategoryId = 22, IsDeleted = false,
                    Description = "سرویس کلاس فیتنس در خانه شامل برگزاری جلسات تمرینی شخصی یا گروهی در منزل شما است. این کلاس\u200cها ممکن است شامل تمرینات هوازی، قدرتی، HIIT، کار با وزنه یا تمرینات متناسب با اهداف خاص شما مانند کاهش وزن، افزایش قدرت یا بهبود تناسب اندام باشد. این سرویس به افراد این امکان را می\u200cدهد که بدون نیاز به مراجعه به باشگاه، تمرینات خود را در خانه انجام دهند و از راهنمایی و حمایت مربی بهره\u200cمند شوند.",
                    ImageSrc = "/assets/img/homeservice/86.jpg", BasePrice = 2000000 },
                new AcharDomainCore.Entites.HomeService { Id = 87, Title = "پیشنهادفروش خدمات آچار ب شرکت ها", SubCategoryId = 23, IsDeleted = false,
                    Description = "با استفاده از خدمات تخصصی آچار، تجهیزات و زیرساخت\u200cهای فنی شرکت خود را همیشه در بهترین شرایط نگه دارید. ما با ارائه تعمیرات، سرویس\u200cهای دوره\u200cای، تأمین قطعات و پشتیبانی فنی، به شما کمک می\u200cکنیم تا هزینه\u200cهای نگهداری را کاهش داده، بهره\u200cوری را افزایش دهید و از خرابی\u200cهای ناگهانی جلوگیری کنید.",
                    ImageSrc = "/assets/img/homeservice/87.jpg", BasePrice = 5000000 },
                new AcharDomainCore.Entites.HomeService { Id = 88, Title = "خدمات شرکت ویژه شرکت های بزرگ", SubCategoryId = 23, IsDeleted = false,
                    Description = "آچار با ارائه خدمات تخصصی برای شرکت\u200cهای بزرگ، بهره\u200cوری را افزایش داده و هزینه\u200cهای عملیاتی را کاهش می\u200cدهد. این خدمات شامل نگهداری پیشگیرانه برای جلوگیری از خرابی\u200cهای ناگهانی، پشتیبانی ۲۴/۷ برای رفع سریع مشکلات، تأمین قطعات یدکی با تضمین کیفیت، بهینه\u200cسازی و ارتقای تجهیزات برای بهبود عملکرد و کاهش مصرف انرژی، و همچنین ارائه راهکارهای اختصاصی متناسب با نیازهای هر سازمان است.",
                    ImageSrc = "/assets/img/homeservice/88.jpg", BasePrice = 8000000 },
                new AcharDomainCore.Entites.HomeService { Id = 89, Title = "استخدام بادیگارد", SubCategoryId = 24, IsDeleted = false,
                    Description = "سرویس استخدام بادیگارد خدمات حفاظت شخصی، امنیتی و تشریفاتی را با تیمی از افراد حرفه\u200cای، آموزش\u200cدیده و مجهز ارائه می\u200cدهد تا امنیت افراد، مدیران، سلبریتی\u200cها و رویدادهای خاص تضمین شود.",
                    ImageSrc = "/assets/img/homeservice/89.jpg", BasePrice = 3000000 },
                new AcharDomainCore.Entites.HomeService { Id = 90, Title = "استخدام راننده", SubCategoryId = 24, IsDeleted = false,
                    Description = "سرویس استخدام راننده ارائه\u200cدهنده رانندگان حرفه\u200cای، با\u200cتجربه و قابل\u200cاعتماد برای جابه\u200cجایی ایمن و راحت مدیران، افراد مهم و سازمان\u200cها با خودروهای شخصی یا تشریفاتی است.",
                    ImageSrc = "/assets/img/homeservice/90.jpg", BasePrice = 2000000 }

                    );
        }

    }
}
